<a href="https://colab.research.google.com/github/aditya-ailsinghani/fifa22-player-value-analytics/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import os

PROJECT_PATH = "/content/drive/MyDrive/Projects/Fifa_Analytics"
os.chdir(PROJECT_PATH)

print("Current directory:", os.getcwd())

Current directory: /content/drive/MyDrive/Projects/Fifa_Analytics

In [6]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

In [7]:
df = pd.read_csv("FIFA22_official_data.csv")

In [8]:
df.shape

(16710, 65)

In [9]:
df.head()

       ID             Name  Age                                             Photo Nationality                                 Flag  Overall  Potential                Club                                Club Logo    Value   Wage  Special Preferred Foot  International Reputation  Weak Foot  Skill Moves     Work Rate         Body Type Real Face                     Position  Jersey Number        Joined Loaned From Contract Valid Until Height Weight  Crossing  Finishing  HeadingAccuracy  ShortPassing  Volleys  Dribbling  Curve  FKAccuracy  LongPassing  BallControl  Acceleration  SprintSpeed  Agility  Reactions  Balance  ShotPower  Jumping  Stamina  Strength  LongShots  Aggression  Interceptions  Positioning  Vision  Penalties  Composure  Marking  StandingTackle  SlidingTackle  GKDiving  GKHandling  GKKicking  GKPositioning  GKReflexes Best Position  Best Overall Rating Release Clause  DefensiveAwareness
0  212198  Bruno Fernandes   26  https://cdn.sofifa.com/players/212/198/22_60.png    Portugal  https://cdn.sofifa.com/flags/pt.png       88         89   Manchester United   https://cdn.sofifa.com/teams/11/30.png  €107.5M  €250K     2341          Right                       3.0        3.0          4.0    High/ High            Unique       Yes  <span class="pos pos18">CAM           18.0  Jan 30, 2020         NaN                 2025  179cm   69kg      87.0       83.0             64.0          91.0     87.0       83.0   87.0        87.0         88.0         87.0          77.0         73.0     80.0       91.0     79.0       89.0     73.0     91.0      70.0       89.0        78.0           66.0         87.0    90.0       91.0       87.0      NaN            73.0           65.0      12.0        14.0       15.0            8.0        14.0           CAM                 88.0        €206.9M                72.0
1  209658      L. Goretzka   26  https://cdn.sofifa.com/players/209/658/22_60.png     Germany  https://cdn.sofifa.com/flags/de.png       87         88   FC Bayern München   https://cdn.sofifa.com/teams/21/30.png     €93M  €140K     2314          Right                       4.0        4.0          3.0  High/ Medium            Unique       Yes  <span class="pos pos11">LDM            8.0   Jul 1, 2018         NaN                 2026  189cm   82kg      75.0       82.0             86.0          86.0     69.0       84.0   76.0        75.0         84.0         87.0          78.0         83.0     76.0       88.0     71.0       85.0     79.0     88.0      88.0       86.0        81.0           86.0         85.0    84.0       60.0       82.0      NaN            85.0           77.0      13.0         8.0       15.0           11.0         9.0            CM                 87.0        €160.4M                74.0
2  176580        L. Suárez   34  https://cdn.sofifa.com/players/176/580/22_60.png     Uruguay  https://cdn.sofifa.com/flags/uy.png       88         88  Atlético de Madrid  https://cdn.sofifa.com/teams/240/30.png   €44.5M  €135K     2307          Right                       5.0        4.0          3.0  High/ Medium            Unique       Yes   <span class="pos pos24">RS            9.0  Sep 25, 2020         NaN                 2022  182cm   83kg      80.0       93.0             84.0          83.0     90.0       83.0   86.0        82.0         77.0         86.0          76.0         69.0     75.0       92.0     78.0       89.0     69.0     78.0      85.0       88.0        87.0           41.0         91.0    84.0       83.0       87.0      NaN            45.0           38.0      27.0        25.0       31.0           33.0        37.0            ST                 88.0         €91.2M                42.0
3  192985     K. De Bruyne   30  https://cdn.sofifa.com/players/192/985/22_60.png     Belgium  https://cdn.sofifa.com/flags/be.png       91         91     Manchester City   https://cdn.sofifa.com/teams/10/30.png  €125.5M  €350K     2304          Right                       4.0        5.0          4.0    High/ High            Unique       Yes  <span class="pos pos13">RCM           17.0  Aug 30, 2015         NaN                 2025  181cm   70kg      94.0       82.0             55.0          94.0     82.0       88.0   85.0        83.0         93.0         91.0          76.0         76.0     79.0       91.0     78.0       91.0     63.0     89.0      74.0       91.0        76.0           66.0         88.0    94.0       83.0       89.0      NaN            65.0           53.0      15.0        13.0        5.0           10.0        13.0            CM                 91.0        €232.2M                68.0
4  224334         M. Acuña   29  https://cdn.sofifa.com/players/224/334/22_60.png   Argentina  https://cdn.sofifa.com/flags/ar.png       84         84          Sevilla FC  https://cdn.sofifa.com/teams/481/30.png     €37M   €45K     2292           Left                       2.0        3.0          4.0    High/ High  Stocky (170-185)        No    <span class="pos pos7">LB           19.0  Sep 14, 2020         NaN                 2024  172cm   69kg      87.0       66.0             58.0          82.0     68.0       87.0   88.0        75.0         78.0         88.0          77.0         76.0     83.0       83.0     90.0       82.0     63.0     90.0      80.0       81.0        84.0           79.0         81.0    82.0       76.0       87.0      NaN            84.0           82.0       8.0        14.0       13.0           13.0        14.0            LB                 84.0         €77.7M                80.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16710 entries, 0 to 16709
Data columns (total 65 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        16710 non-null  int64
 1   Name                      16710 non-null  object
 2   Age                       16710 non-null  int64
 3   Photo                     16710 non-null  object
 4   Nationality               16710 non-null  object
 5   Flag                      16710 non-null  object
 6   Overall                   16710 non-null  int64
 7   Potential                 16710 non-null  int64
 8   Club                      16446 non-null  object
 9   Club Logo                 16710 non-null  object
 10  Value                     16710 non-null  object
 11  Wage                      16710 non-null  object
 12  Special                   16710 non-null  int64
 13  Preferred Foot            16710 non-null  object
 14  International Reputation  16710 non-null  float64
 15  Weak Foot                 16710 non-null  float64
 16  Skill Moves               16710 non-null  float64
 17  Work Rate                 16710 non-null  object
 18  Body Type                 16681 non-null  object
 19  Real Face                 16681 non-null  object
 20  Position                  16684 non-null  object
 21  Jersey Number             16684 non-null  float64
 22  Joined                    15198 non-null  object
 23  Loaned From               1132 non-null   object
 24  Contract Valid Until      16359 non-null  object
 25  Height                    16710 non-null  object
 26  Weight                    16710 non-null  object
 27  Crossing                  16710 non-null  float64
 28  Finishing                 16710 non-null  float64
 29  HeadingAccuracy           16710 non-null  float64
 30  ShortPassing              16710 non-null  float64
 31  Volleys                   16673 non-null  float64
 32  Dribbling                 16710 non-null  float64
 33  Curve                     16673 non-null  float64
 34  FKAccuracy                16710 non-null  float64
 35  LongPassing               16710 non-null  float64
 36  BallControl               16710 non-null  float64
 37  Acceleration              16710 non-null  float64
 38  SprintSpeed               16710 non-null  float64
 39  Agility                   16673 non-null  float64
 40  Reactions                 16710 non-null  float64
 41  Balance                   16673 non-null  float64
 42  ShotPower                 16710 non-null  float64
 43  Jumping                   16673 non-null  float64
 44  Stamina                   16710 non-null  float64
 45  Strength                  16710 non-null  float64
 46  LongShots                 16710 non-null  float64
 47  Aggression                16710 non-null  float64
 48  Interceptions             16702 non-null  float64
 49  Positioning               16702 non-null  float64
 50  Vision                    16673 non-null  float64
 51  Penalties                 16710 non-null  float64
 52  Composure                 16459 non-null  float64
 53  Marking                   892 non-null    float64
 54  StandingTackle            16710 non-null  float64
 55  SlidingTackle             16673 non-null  float64
 56  GKDiving                  16710 non-null  float64
 57  GKHandling                16710 non-null  float64
 58  GKKicking                 16710 non-null  float64
 59  GKPositioning             16710 non-null  float64
 60  GKReflexes                16710 non-null  float64
 61  Best Position             16710 non-null  object
 62  Best Overall Rating       16710 non-null  float64
 63  Release Clause            14961 non-null  object
 64  DefensiveAwareness        15818 non-null  float64
dtypes: float64(40), int64(5), object(20)
memory usage: 8.3+ MB

In [11]:
df.isna().sum().sort_values(ascending=False).head(15)

Marking                 15818
Loaned From             15578
Release Clause           1749
Joined                   1512
DefensiveAwareness        892
Contract Valid Until      351
Club                      264
Composure                 251
Balance                    37
Volleys                    37
Jumping                    37
Agility                    37
Curve                      37
SlidingTackle              37
Vision                     37
dtype: int64

In [12]:
columns = df.columns.tolist()
columns

['ID',
 'Name',
 'Age',
 'Photo',
 'Nationality',
 'Flag',
 'Overall',
 'Potential',
 'Club',
 'Club Logo',
 'Value',
 'Wage',
 'Special',
 'Preferred Foot',
 'International Reputation',
 'Weak Foot',
 'Skill Moves',
 'Work Rate',
 'Body Type',
 'Real Face',
 'Position',
 'Jersey Number',
 'Joined',
 'Loaned From',
 'Contract Valid Until',
 'Height',
 'Weight',
 'Crossing',
 'Finishing',
 'HeadingAccuracy',
 'ShortPassing',
 'Volleys',
 'Dribbling',
 'Curve',
 'FKAccuracy',
 'LongPassing',
 'BallControl',
 'Acceleration',
 'SprintSpeed',
 'Agility',
 'Reactions',
 'Balance',
 'ShotPower',
 'Jumping',
 'Stamina',
 'Strength',
 'LongShots',
 'Aggression',
 'Interceptions',
 'Positioning',
 'Vision',
 'Penalties',
 'Composure',
 'Marking',
 'StandingTackle',
 'SlidingTackle',
 'GKDiving',
 'GKHandling',
 'GKKicking',
 'GKPositioning',
 'GKReflexes',
 'Best Position',
 'Best Overall Rating',
 'Release Clause',
 'DefensiveAwareness']

Height, Weight -> Numeric

In [13]:
df["Height_cm"] = df["Height"].str.replace("cm", "").astype(int)
df["Weight_kg"] = df["Weight"].str.replace("kg", "").astype(int)

df = df.drop(columns=["Height", "Weight"])

In [14]:
df[["Height_cm", "Weight_kg"]].head()

   Height_cm  Weight_kg
0        179         69
1        189         82
2        182         83
3        181         70
4        172         69

In [15]:
df.shape #check if there aren't any extra columns now

(16710, 65)

Money columns (Eur)->Numeric

In [16]:
import re
import pandas as pd
import numpy as np

def parse_money(value):
    if pd.isna(value):
        return np.nan
    s = str(value).strip().replace("€", "").replace(",", "")
    if s.endswith("M"):
        return float(s[:-1]) * 1_000_000
    if s.endswith("K"):
        return float(s[:-1]) * 1_000
    # sometimes it may already be a plain number-like string
    return float(s)

In [17]:
df["Value_EUR"] = df["Value"].apply(parse_money)
df["Wage_EUR"] = df["Wage"].apply(parse_money)
df["Release_Clause_EUR"] = df["Release Clause"].apply(parse_money)

df = df.drop(columns=["Value", "Wage", "Release Clause"])

In [18]:
df[["Value_EUR", "Wage_EUR", "Release_Clause_EUR"]].head()

     Value_EUR  Wage_EUR  Release_Clause_EUR
0  107500000.0  250000.0         206900000.0
1   93000000.0  140000.0         160400000.0
2   44500000.0  135000.0          91200000.0
3  125500000.0  350000.0         232200000.0
4   37000000.0   45000.0          77700000.0

Check whats missing

In [22]:
df.isna().sum().sort_values(ascending=False).head(25)

Loaned From                 15578
Release_Clause_EUR           1749
Joined                       1512
DefensiveAwareness            892
Contract Valid Until          351
Club                          264
Composure                     251
Volleys                        37
Vision                         37
Jumping                        37
Balance                        37
SlidingTackle                  37
Agility                        37
Curve                          37
Body Type                      29
Real Face                      29
Position                       26
Jersey Number                  26
Positioning                     8
Interceptions                   8
Preferred Foot                  0
Special                         0
Weak Foot                       0
International Reputation        0
Work Rate                       0
dtype: int64

In [20]:
#Gotta drop Marking
df = df.drop(columns=["Marking"])

In [23]:
categorical_cols = [
    "Loaned From",
    "Joined",
    "Contract Valid Until",
    "Club",
    "Body Type",
    "Real Face",
    "Position",
    "Jersey Number"
]

df[categorical_cols] = df[categorical_cols].fillna("Unknown")

In [24]:
df[categorical_cols].isna().sum()

Loaned From             0
Joined                  0
Contract Valid Until    0
Club                    0
Body Type               0
Real Face               0
Position                0
Jersey Number           0
dtype: int64

In [25]:
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

In [26]:
df.isna().sum().sort_values(ascending=False).head(10)

ID             0
Name           0
Age            0
Photo          0
Nationality    0
Flag           0
Overall        0
Potential      0
Club           0
Club Logo      0
dtype: int64

Preprocessing check

In [27]:
# 1) Confirm no missing values remain
print("Total missing values:", df.isna().sum().sum())

# 2) Confirm final shape
print("Shape:", df.shape)

# 3) Quick look at column types (helps later for modeling)
df.dtypes.value_counts()

Total missing values: 0
Shape: (16710, 64)

float64    41
object     16
int64       7
Name: count, dtype: int64

In [28]:
clean_path = "FIFA22_cleaned.csv"
df.to_csv(clean_path, index=False)

print("Saved:", clean_path)

Saved: FIFA22_cleaned.csv